# Generated by Django 4.2.2 on 2023-10-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
