# Generated by Django 4.2.2 on 2023-10-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_task_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.RemoveField(
            model_name='task',
            name='catagory',
        ),
    ]
